[package]
name = "pong"
version = "0.1.0"
authors = ["Jonathon <jyallop21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.3", features = ["canvas", "tokio", "debug"]}
rand = "0.8.3"